language: java
jdk:
  - oraclejdk7
  - oraclejdk8

sudo: false

before_install:
  - chmod +x gradlew

install:
  - ./gradlew assemble

script:
  - ./gradlew check -x integrationTest

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
   directories:
   - $HOME/.gradle/caches/